#define STRINGLENGTHSMM 200
#define STRINGLENGTHTMM 50
#define STRINGLENGTHPLM 50
#define STRINGLENGTHOTHER 300
#define STRINGLENGTHHEADSTRING 10
#define STRINGLENGTHENDSTRING 10

#define STRINGLENGTHDATASTRING STRINGLENGTHSMM+STRINGLENGTHTMM+STRINGLENGTHPLM 
#define STRINGLENGTHSTRINGTOSEND STRINGLENGTHDATASTRING+STRINGLENGTHOTHER+STRINGLENGTHHEADSTRING+STRINGLENGTHENDSTRING
